[mcp_servers.shadcn]
command = "bunx"
args = [ "shadcn@latest", "mcp" ]

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=vxmzwszlnpgjnfqdnzzs"

[mcp_servers.mcp-docs-server]
command = "npx"
args = [ "-y", "@assistant-ui/mcp-docs-server" ]

[features]
rmcp_client = true
